name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  verify:
    strategy:
      matrix:
        jversion: ["11", "17"]
        jdistribution: ["temurin"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jversion }}
          distribution: ${{ matrix.jdistribution }}
          cache: "maven"

      - name: Test Maven
        run: mvn verify
